M48
; DRILL file {KiCad 9.0.5} date 2026-06-01T00:15:45+0200
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-06-01T00:15:45+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.5
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X93.5Y-93.5
X93.5Y-106.0
X93.5Y-118.5
X155.5Y-93.5
X155.5Y-106.0
X155.5Y-118.5
M30
